import numpy as np


# def calculate_fitness(route,
#                       distance_matrix):
#     """
#     calculate_fitness function: total distance traveled by the car.

#     Parameters:
#         - route (list): A list representing the order of nodes visited in the route.
#         - distance_matrix (numpy.ndarray): A matrix of the distances between nodes.
#             A 2D numpy array where the element at position [i, j] represents the distance between node i and node j.
#     Returns:
#         - float: The negative total distance traveled (negative because we want to minimize distance).
#            Returns a large negative penalty if the route is infeasible.
#     """
#     total_distance = 0
    
#     # add your code here.
#     for i in range(len(route) - 1):
#         node1, node2 = route[i], route[i + 1]
#         distance = distance_matrix[node1, node2]
        
#         if distance == 10000:  # Infeasible route check
#             return -1e6  # Large negative penalty

#         total_distance += distance
    
#     return total_distance
#UPDATED FUNCTION
def calc_fitness_multiple_cars(route, distance_matrix, num_cars):
    """
    Calculate total distance for multiple cars.
    - Ensures all deliveries are covered while minimizing longest route.

    Parameters:
        - route (list of lists): Each sublist represents a route for one car.
        - distance_matrix (numpy.ndarray): Matrix of distances.
        - num_cars (int): Number of cars.

    Returns:
        - float: The longest distance traveled by a single car (to balance workload).
    """
    if not isinstance(route[0], list):  # Ensure route is already split per car
        # If the route is a single list, split it manually
        route = [list(r) for r in np.array_split(route, num_cars)]

    total_distances = []

    for sub_route in route:
        distance = 0
        prev_node = 0  # Start at depot
        for node in sub_route:
            distance += distance_matrix[prev_node, node]
            prev_node = node
        distance += distance_matrix[prev_node, 0]  # Return to depot
        total_distances.append(distance)

    return max(total_distances)  # Minimize the longest distance






def select_in_tournament(population,
                         scores,
                         number_tournaments=4,
                         tournament_size=3):
    """
    Tournament selection for genetic algorithm.

    Parameters:
        - population (list): The current population of routes.
        - scores (np.array): The calculate_fitness scores corresponding to each individual in the population.
        - number_tournaments (int): The number of the tournamnents to run in the population.
        - tournament_size (int): The number of individual to compete in the tournaments.

    Returns:
        - list: A list of selected individuals for crossover.
    """
    selected = []
    
    # add your code here.
    for _ in range(number_tournaments):
        idx=np.random.choice(len(population),tournament_size,replace=False)
        best_idx = idx[np.argmax(scores[idx])]
        selected.append(population[best_idx])
    
    return selected





# def order_crossover(parent1, parent2):
#     """
#     Order crossover (OX) for permutations.

#     Parameters:
#         - parent1 (list): The first parent route.
#         - parent2 (list): The second parent route.

#     Returns:
#         - list: The offspring route generated by the crossover.
#     """
#     size = len(parent1)
#     start, end = sorted(np.random.choice(range(size), 2, replace=False))
#     offspring = [None] * size
#     offspring[start:end + 1] = parent1[start:end + 1]
#     fill_values = [x for x in parent2 if x not in offspring[start:end + 1]]
#     idx = 0
#     for i in range(size):
#         if offspring[i] is None:
#             offspring[i] = fill_values[idx]
#             idx += 1
#     return offspring
#UPDATED FUNCTION
def pmx_crossover(parent1, parent2):
    """
    Partially Mapped Crossover (PMX) for genetic algorithms.
    Applies PMX separately to each car's route.

    Parameters:
        - parent1 (list of lists): First parent, where each sublist represents a car's route.
        - parent2 (list of lists): Second parent, structured similarly.

    Returns:
        - list of lists: Offspring with routes for multiple cars.
    """
    def apply_pmx(p1, p2):
        """ Apply PMX on a single route (sublist) """
        size = len(p1)
        child = [-1] * size  

        start, end = sorted(np.random.choice(range(size), 2, replace=False))

        child[start:end + 1] = p1[start:end + 1]

        mapping = {p1[i]: p2[i] for i in range(start, end + 1)}

        for i in range(size):
            if child[i] == -1:  
                candidate = p2[i]
                while candidate in mapping:  
                    candidate = mapping[candidate]
                child[i] = candidate

        return child

    # Apply PMX to each car's route separately
    return [apply_pmx(r1, r2) for r1, r2 in zip(parent1, parent2)]





# def mutate(route,
#            mutation_rate = 0.1):
#     """
#     Mutation operator: swap two nodes in the route.

#     Parameters:
#         - route (list): The route to mutate.
#         - mutation_rate (float): The chance to mutate an individual.
#     Returns:
#         - list: The mutated route.
#     """
#     if np.random.rand() < mutation_rate:
#         i, j = np.random.choice(len(route), 2, replace=False)
#         route[i], route[j] = route[j], route[i]
#     return route
#UPDATED FUNCTION
def adaptive_mutate(route, mutation_rate, diversity_factor=0.2):
    """
    Applies adaptive mutation based on population diversity.

    Parameters:
        - route (list): The route to mutate.
        - mutation_rate (float): Base mutation rate.
        - diversity_factor (float): Scaling factor to adjust mutation rate dynamically.

    Returns:
        - list: Mutated route.
    """
    adaptive_rate = mutation_rate + np.random.uniform(-diversity_factor, diversity_factor)
    
    if np.random.rand() < max(0.01, adaptive_rate):  # Ensure mutation rate doesn't drop too low
        i, j = np.random.choice(len(route), 2, replace=False)
        route[i], route[j] = route[j], route[i]
    
    return route




    
# def generate_unique_population(population_size, num_nodes):
#     """
#     Generate a unique population of individuals for a genetic algorithm.

#     Each individual in the population represents a route in a graph, where the first node is fixed (0) and the 
#     remaining nodes are a permutation of the other nodes in the graph. This function ensures that all individuals
#     in the population are unique.

#     Parameters:
#         - population_size (int): The desired size of the population.
#         - num_nodes (int): The number of nodes in the graph, including the starting node.

#     Returns:
#         - list of lists: A list of unique individuals, where each individual is represented as a list of node indices.
#     """
#     population = set()
#     while len(population) < population_size:
#         individual = [0] + list(np.random.permutation(np.arange(1, num_nodes)))
#         population.add(tuple(individual))
#     return [list(ind) for ind in population]

#UPDATED FUNCTION
def generate_unique_population_multiple_cars(population_size, num_nodes, num_cars):
    """
    Generate a unique population of individuals for a genetic algorithm.
    Each individual represents routes for multiple cars.

    Parameters:
        - population_size (int): Number of individuals in the population.
        - num_nodes (int): Number of delivery locations (excluding the depot).
        - num_cars (int): Number of cars available for deliveries.

    Returns:
        - list of lists: A list of unique individuals, where each individual 
          consists of multiple sub-routes (one per car).
    """
    population = set()

    while len(population) < population_size:
        # Generate a shuffled list of delivery locations
        locations = list(np.random.permutation(np.arange(1, num_nodes)))

        # Split locations into 'num_cars' separate routes
        split_routes = np.array_split(locations, num_cars)
        
        # Convert back to lists and add depot (node 0) at the beginning of each route
        individual = [[0] + list(route) for route in split_routes]
        
        population.add(tuple(tuple(sub_route) for sub_route in individual))  # Ensure uniqueness

    return [list(map(list, ind)) for ind in population]  # Convert back to list format

